config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'careers', :to => 'static_pages#careers'
  get 'team', :to => 'static_pages#team'
  resource :dashboard, :only => [:show]
  resources :courses, :only => [:index, :show] do
    resources :enrollments, :only => [:create, :destroy]
  end 
  resources :lessons, :only => [:show]
  namespace :instructor do
    resources :lessons, :only => [:update]
    resources :sections, :only => [] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show, :edit, :update] do
      resources :sections, :only => [:create, :update]
    end
  end
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

	private



	helper_method :current_enrollment
	def current_enrollment
	
		@current_enrollment = current_user.enrollments.where( course_id: @course.id ).first
	


	end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_course, :only => [:show, :edit, :update]

	def new
		@course = Course.new
	end

	def create
		@course = current_user.courses.create(course_params)

		if @course.valid?
			redirect_to instructor_course_path(@course)
		else
			render :new, :status => :unprocessable_entity
		end
	end

	def edit
	end

	def show
		@section = Section.new
		@lesson = Lesson.new
	end

	def update
		current_course.update_attributes(course_params)
		if current_course.valid?
			redirect_to instructor_course_path(current_course)
		else
			render :edit, :status => :unprocessable_entity
		end
	end

	private

	def course_params
		params.require(:course).permit(:title, :description, :cost, :image)
	end

	helper_method :current_course
	def current_course
		@current_course ||= Course.find(params[:id])
	end


	def require_authorized_for_current_course
		if current_course.user != current_user
			render :text => 'Unauthorized', :status => :unauthorized
		end
	end



end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_section, :only => [ :create]
	before_action :require_authorized_for_current_lesson, :only => [:update]


	def create
		@lesson = current_section.lessons.create(lesson_params)
		if @lesson.valid?
			redirect_to instructor_course_path(current_section.course)
		else 
			render :new, :status => :unprocessable_entity
		end

	end

	def update
		current_lesson.update_attributes(lesson_params)
		render :text => 'updated!'
	end


	private

	def current_lesson
		@current_lesson ||= Lesson.find(params[:id])
	end

	helper_method :current_section
	def current_section
		@current_section ||= Section.find(params[:section_id])
	end

	def lesson_params
		params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
	end

	def require_authorized_for_current_lesson
		if current_lesson.section.course.user != current_user
			render :text => 'Unauthorized', :status => :unauthorized
		end
	end

	def require_authorized_for_current_section
		if current_section.course.user != current_user
			return render :text => 'Unauthorized', :status => :unauthorized
		end
	end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
	before_action :authenticate_user!
	
	def new
		@section = Section.new
	end

	def create
		@section = current_course.sections.create(section_params)

		if @section.valid?
			redirect_to instructor_course_path(current_course)
		else
			render :new, :status => :unprocessable_entity
		end
	end

	def update
		@section = Section.find(params[:id])
		@section.update_attributes(section_params)
		render :text => 'updated!'
	end

	private

	def section_params
		params.require(:section).permit(:title, :row_order_position)
	end

	helper_method :current_course
	def current_course
		@current_course ||= Course.find(params[:course_id])
	end

	def require_authorized_for_current_course
		if current_course.user != current_user
			render :text => 'Unauthorized', :status => :unauthorized
		end
	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1> Edit Course </h1>
	<%= simple_form_for current_course, :url => instructor_course_path(current_course) do |f| %>
		<%= f.input :title %>
		<%= f.input :description %>
		<%= f.input :cost %>
		<%= f.input :image %>
		<br />
		<%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
		<br />
	<% end %>
</div>

app/views/instructor/courses/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1> New Course </h1>
	<%= simple_form_for @course, :url => instructor_courses_path do |f| %>
		<%= f.input :title %>
		<%= f.input :description %>
		<%= f.input :cost %>
		<br />
		<%= f.submit 'Create', :class => 'btn btn-primary' %>
		<br />
	<% end %>
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.lessons').sortable({
      update: function( event, ui ) {
      	$.ajax({
      		type: 'PUT',
      		url: ui.item.data('update-url'),
      		dataType: 'json',
      		data: { lesson: {row_order_position: ui.item.index() } }
      	});
      }
  	});
	});

	$(function() {
		$('.sections').sortable({
			update: function( event, ui ) {
				$.ajax({
					type: 'PUT',
					url: ui.item.data('update-url'),
					dataType: 'json',
					data: { section: {row_order_position: ui.item.index() } }

				});
			}
		});
	});

	$(function() {
		$('.sections button').click( function() {
			var actionURL = $(this).data('lesson-url');
			$('#newLessonModal form').attr('action', actionURL );

		});

	});
</script>


<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1 class='text-center'><%= current_course.title %></h1>
	<%= image_tag current_course.image, :class => 'img-responsive' %> 
	<div class='text-center'>
		<%= link_to 'Preview as student', course_path(current_course), :class => 'btn btn-primary' %>
		<!-- Button trigger modal -->
		<button class="btn btn-primary" data-toggle="modal" data-target="#newSectionModal">
			New Section
		</button>
		<%= link_to 'Edit course', edit_instructor_course_path(current_course), :class => 'btn btn-primary' %>
	</div>
	<ul class='sections'>
		<% current_course.sections.rank(:row_order).each do |section| %>

			<li data-update-url="<%= instructor_course_section_path(section.course, section.id) %> " class = 'section-li'> 	<div class = 'header'>
					<span class='glyphicon glyphicon-list'></span>
					<%= link_to section.title, '#' %>
					<!-- Button trigger modal -->
					<button class="btn btn-primary btn-xs pull-right" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
					  New Lesson
					</button>
				</div>
				<ul class='lessons'>
					<% section.lessons.rank(:row_order).each do |lesson| %>
						<li data-update-url="<%= instructor_lesson_path(lesson.id) %>" >
							<div class='col-xs-1' >
								<span class='glyphicon glyphicon-list'></span>
							</div>
							<div class='col-xs-11 text-center' >
								<p>
									<b><%= link_to lesson.title, '#' %></b>
								</p>
								<p>
									<%= lesson.subtitle %>
								</p>
							</div>
							<br class='clr' />
						</li>
					<% end %>
				</ul>
			</li>
		<% end %>
	</ul>
	<br />
	<div class='col-sm-9 col-xs-12'>	
		<p><%= current_course.description %></p>
	</div>
	<div class='col-sm-3 col-xs-12'>
		<p><%= number_to_currency current_course.cost %></p>
	</div>
</div>



<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new Section</h4>
      </div>
      <div class="modal-body">
        <h2><%= link_to current_course.title, courses_path(current_course) %></h2>
        <%= simple_form_for @section, :url => instructor_course_sections_path(current_course) do |f| %>
        	<%= f.input :title %>
        	<%= f.submit 'Add Section', :class => 'btn btn-primary' %>
        <% end %>
      </div>
      
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new Lesson</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @lesson, :url => '#' do |f| %>
        	<%= f.input :title %>
        	<%= f.input :subtitle %>
        	<%= f.input :video %>

        	<%= f.submit 'Add Lesson', :class => 'btn btn-primary' %>
        <% end %>
        
      </div>
      
    </div>
  </div>
</div>